@startuml
class BlockedTar {
  
}

class DepotTarHeader {
  
}

class DepotTar {
  
}

class DepotTarPossessionPowerSector {
  
}

class DepotTarSector {
  
}

class DutyOCCRoster {
  
}

class Menu {
  
}

class OCCRoster {
  
}

class OCCTarTVF {
  
}

class OCCTrainAuthCC {
  
}

class OCCTrainAuthNEL {
  
}

class OCCTrainAuthPFR {
  
}

class OCCTrainAuthPreview_DTL {
  
}

class OCCTrainAuthPreview_NEL {
  
}

class OCCTrainAuthTC {
  
}

class OCCTVFAck {
  
}

class OCCTVFAckRemark {
  
}

class Parameter {
  
}

class RosterRole {
  
}

class Sector {
  
}

class TarHeader {
  
}

class Tar {
  
}

class TarAccessRequirement {
  
}

class TarApproval {
  
}

class TarOtherProtection {
  
}

class TarPossessionLimit {
  
}

class TarPossessionPlan {
  
}

class TarPossessionPowerSector {
  
}

class TarSector {
  
}

class TarStation {
  
}

class TarWorkingLimit {
  
}

class TractionPower {
  
}

class TractionPowerDetail {
  
}

class TypeOfWork {
  
}

class User {
  
}

class UserRail {
  
}

class UserRegistration {
  
}

class Company {
  
}

class SystemAccess {
  
}

class SystemAccessRoles {
  
}

class Role {
  
}

class WFStatus {
  
}

class BlockedTarDao {
  + public GetBlockedTarDate(line: string, tracktype: string, accessDate: DateTime): BlockedTar()
  + public GetBlockedTarDates(line: string, tracktype: string, accessDate: DateTime): List<BlockedTar>()
}

class Db {
  + public Read(spname: string, make: Func<IDataReader, T>, parms: object[]): IEnumerable<T>()
  + public Scalar(spname: string, parms: object[]): object()
  + public Insert(spname: string, parms: object[]): int()
  + public Update(spname: string, parms: object[]): int()
  + public Delete(spname: string, parms: object[]): int()
  + CreateConnection(): DbConnection()
  + CreateCommand(spname: string, conn: DbConnection, parms: object[]): DbCommand()
  + CreateAdapter(command: DbCommand): DbDataAdapter()
  + public static AddParameters(command: DbCommand, parms: object[]): void()
}

class DbExtentions {
  
}

class DepotBlockedTarDao {
  + public GetBlockedTarDate(line: string, accessDate: DateTime): BlockedTar()
  + public GetDepotBlockedTarDates(line: string, accessDate: DateTime): List<BlockedTar>()
}

class DepotTarDao {
  + public GetTarEnquiryResult_Header(uid: string, line: string, TrackType: string, tarType: string, accessType: string, tarStatusId: string, accessDateFrom: string, accessDateTo: string, department: string, user: string): List<DepotTarHeader>()
  + public GetTarByTarId(tarId: int): DepotTar()
  + public GetTarForPossessionPlanReport(line: string, tracktype: string, accessType: string, accessDateFrom: string, accessDateTo: string): List<DepotTar>()
  + public CancelTarByTarId(tarId: int, uid: string): void()
  + public WithdrawTarByTarId(tarId: int, uid: string, remark: string): void()
}

class DepotTarPossessionPowerSectorDao {
  + public GetTarPossessionPowerSectorByPossessionId(possessionId: int): List<DepotTarPossessionPowerSector>()
}

class DepotTarSectorDao {
  + public GetTarSectorsByAccessDateAndLine(accessDate: DateTime, line: string, location: string): List<DepotTarSector>()
  + public GetTarSectorsByTarId(tarId: int): List<DepotTarSector>()
}

class DutyOCCRosterDao {
  + public GetDutyOCCRosterByParameters(line: string, tracktype: string, operationDate: string, shift: string, rosterCode: string, id: int, locationcode: string): DutyOCCRoster()
  + public GetDutyOCCRosterByParameters(userID: int, line: string, tracktype: string, operationDate: string, shift: string): List<DutyOCCRoster>()
  + public GetDutyOCCRosterByParametersForTVFAck(userID: int, line: string, tracktype: string, operationDate: string, shift: string, locationcode: string): List<DutyOCCRoster>()
  + public InsertToDutyOCCRosterTable(dtOCCDutyRoster: DataTable): void()
}

class Extensions {
  + public static AsId(item: object, defaultId: int): int()
  + public static AsInt(item: object, defaultInt: int): int()
  + public static AsDouble(item: object, defaultDouble: double): double()
  + public static AsString(item: object, defaultString: string): string()
  + public static AsDateTime(item: object, defaultDateTime: DateTime): DateTime()
  + public static AsBool(item: object, defaultBool: bool): bool()
  + public static AsByteArray(s: string): byte[]()
  + public static AsBase64String(item: object): string()
  + public static AsGuid(item: object): Guid()
  + public static OrderBy(sql: string, sortExpression: string): string()
  + public static CommaSeparate(source: IEnumerable<T>, func: Func<T, U>): string()
}

class MenuDao {
  + public getParentMenuByUserRole(userid: string, isInternet: string): IEnumerable<Menu>()
  + public getChildMenuByUserRole(userid: string, mid: string, isInternet: string): IEnumerable<Menu>()
}

class OCCRosterDao {
  + public GetOCCRosterByLineAndRole(line: string, tracktype: string, role: string, locationcode: string): List<OCCRoster>()
}

class OCCTarTVFDao {
  + public GetOCCTVFAckByParameters(stationId: int, accessDate: DateTime): List<OCCTarTVF>()
}

class OCCTrainAuthCCDao {
  + public GetOCCGetOCCAuthorisationCCByParameters(userId: int, line: string, tracktype: string, operationDate: DateTime, accessDate: DateTime): List<OCCTrainAuthCC>()
  + public UpdateOCCAuthorisationCCByParameters(userId: int, occAuthId: int, occLevel: int, line: string, tracktype: string, remarksCC: string): void()
}

class OCCTrainAuthDao_NEL {
  + public GetOCCGetOCCAuthorisationNELByParameters(userId: int, line: string, tracktype: string, operationDate: DateTime, accessDate: DateTime, rosterCode: string): List<OCCTrainAuthNEL>()
  + public UpdateOCCAuthorisationNELByParameters(userId: int, occAuthId: int, occLevel: int, line: string, tracktype: string, remarks: string, selectionValue: string): void()
  + public UpdateOCCAuthorisationNELRemark(userId: int, occAuthId: int, line: string, tracktype: string, remarks: string): void()
}

class OCCTrainAuthPFRDao {
  + public GetOCCGetOCCAuthorisationPFRByParameters(userId: int, line: string, tracktype: string, operationDate: DateTime, accessDate: DateTime): List<OCCTrainAuthPFR>()
  + public UpdateOCCAuthorisationPFRByParameters(userId: int, occAuthId: int, occEndorserId: int, line: string, tracktype: string, remarksPFR: string): void()
  + public UpdateOCCAuthorisationPFRByParameters(userId: int, occAuthId: int, occEndorserId: int, line: string, tracktype: string, remarksPFR: string, selectionValue: string): void()
  + public UpdateOCCAuthorisationPFRByParameters(userId: int, occAuthId: int, occLevel: int, line: string, tracktype: string, remarksPFR: string, selectionValue: string, stationName: string): void()
}

class OCCTrainAuthPreviewDao_DTL {
  + public GetOCCAuthPreviewByParameters(line: string, tracktype: string, operationDate: DateTime, accessDate: DateTime): List<OCCTrainAuthPreview_DTL>()
}

class OCCTrainAuthPreviewDao_NEL {
  + public GetOCCAuthPreviewByParameters(line: string, operationDate: DateTime, accessDate: DateTime): List<OCCTrainAuthPreview_NEL>()
}

class OCCTrainAuthTCDao {
  + public GetOCCGetOCCAuthorisationTCByParameters(userId: int, line: string, tracktype: string, operationDate: DateTime, accessDate: DateTime): List<OCCTrainAuthTC>()
  + public UpdateOCCAuthorisationTCByParameterswithTrackType(userId: int, occAuthId: int, occEndorserId: int, line: string, tracktype: string): void()
  + public UpdateOCCAuthorisationTCByParameters(userId: int, occAuthId: int, occLevel: int, line: string, tracktype: string, selectionValue: string): void()
}

class OCCTVFAckDao {
  + public GetOCCTVFAckByParameters(userId: int, line: string, tracktype: string, operationDate: DateTime, accessDate: DateTime): List<OCCTVFAck>()
  + public GetOCCTVFAckByParametersPreview(userId: int, line: string, tracktype: string, operationDate: DateTime, accessDate: DateTime): List<OCCTVFAck>()
  + public GetOCCTVFAckFromTableByParameters(userId: int, line: string, operationDate: DateTime, accessDate: DateTime): List<OCCTVFAck>()
  + public InsertTVFAckByParameters(operationDate: DateTime, accessDate: DateTime, userId: int, stationId: int, tvfMode: string, tvfDirection1: bool, tvfDirection2: bool): void()
  + public UpdateTVFAckByParameters_CC(operationDate: DateTime, accessDate: DateTime, userId: int, stationId: int, tvfMode: string, tvfDirection1: bool, tvfDirection2: bool): void()
  + public UpdateTVFAckByParameters_PFR(operationDate: DateTime, accessDate: DateTime, userId: int, stationId: int, tvfMode: string, tvfDirection1: bool, tvfDirection2: bool): void()
  + public RejectTVFAckByParameters_PFR(operationDate: DateTime, accessDate: DateTime, userId: int, stationId: int, tvfMode: string, tvfDirection1: bool, tvfDirection2: bool): void()
  + public AddTVFRemarks(userId: int, tvfAckId: int, tvfRemarks: string): void()
  + public GetOCCTVFAckRemarkById(id: int): List<OCCTVFAckRemark>()
}

class ParameterDao {
  + public GetParametersByParaCode(paraCode: string): List<Parameter>()
  + public GetParametersByParaCodeAndParaValue(paraCode: string, paraValue: string): List<Parameter>()
  + public GetParameterbyLineandTrackType(paraCode: string, line: string, TrackType: string, location: string): List<Parameter>()
  + public GetParameterByParaCodeAndParaValue(paraCode: string, paraValue: string, tracktype: string): Parameter()
}

class RosterRoleDao {
  + public GetRosterRoleByLine(line: string, tracktype: string, operationDate: string, shift: string, locationcode: string): List<RosterRole>()
}

class SectorDao {
  + public GetSectorsByLineAndDirection(line: string, direction: string): List<Sector>()
}

class TarAccessRequirementDao {
  + public GetTarAccessReqByTarId(tarId: int): List<TarAccessRequirement>()
}

class TarApprovalDao {
  + public GetTarApprovalsByTarId(tarId: int): List<TarApproval>()
}

class TarDao {
  + public GetTarEnquiryResult_Header(uid: string, line: string, TrackType: string, tarType: string, accessType: string, tarStatusId: string, accessDateFrom: string, accessDateTo: string, department: string, user: string): List<TarHeader>()
  + public GetTarByTarId(tarId: int): Tar()
  + public GetTarForPossessionPlanReport(line: string, tracktype: string, accessType: string, accessDateFrom: string, accessDateTo: string): List<Tar>()
  + public CancelTarByTarId(tarId: int, uid: string): void()
  + public WithdrawTarByTarId(tarId: int, uid: string, withdrawremark: string): void()
}

class TarOtherProtectionDao {
  + public GetTarOtherProtectionByPossessionId(possessionId: int): List<TarOtherProtection>()
}

class TarPossessionLimitDao {
  + public GetTarPossessionLimitByPossessionId(possessionId: int): List<TarPossessionLimit>()
}

class TarPossessionPlanDao {
  + public GetTarPossessionPlanByTarId(tarId: int): TarPossessionPlan()
}

class TarPossessionPowerSectorDao {
  + public GetTarPossessionPowerSectorByPossessionId(possessionId: int): List<TarPossessionPowerSector>()
}

class TarSectorDao {
  + public GetTarSectorsByAccessDateAndLineAndDirection(accessDate: DateTime, line: string, tracktype: string, direction: string): List<TarSector>()
  + public GetTarSectorsByTarId(tarId: int): List<TarSector>()
}

class TarStationDao {
  + public GetTarStationsByTarId(tarId: int): List<TarStation>()
}

class TarWorkingLimitDao {
  + public GetTarWorkingLimitsByPossessionId(possessionId: int): List<TarWorkingLimit>()
}

class TractionPowerDao {
  + public GetTractionPowerByLine(line: string): List<TractionPower>()
}

class TractionPowerDetailDao {
  
}

class TypeOfWorkDao {
  + public GetTypeOfWorkByLine(line: string, Tracktype: string): List<TypeOfWork>()
}

class UserDao {
  + public GetUserByLanId(lanid: string): User()
  + public getRailByUser(userId: string): IEnumerable<UserRail>()
  + public getUserInfo(userId: string): User()
}

class WFStatusDao {
  + public GetWFStatusByLineAndType(line: string, tracktype: string, type: string): List<WFStatus>()
}

class ValidateTarTypeAndDate {
  + public static GetLocation(): string()
  + public static GetLine(): string()
  + public static GetTrackType(): string()
  + private static getWeekNo(): string()
  + private static getlateTarReturnMessage(): string()
  + private static getNormalProtectionTarReturnMessage(): string()
  + private static getNormalPossessionTarReturnMessage(): string()
  + private static getExtendedNormalPossessionTarReturnMessage(): string()
  + private static FirstDateOfWeek(year: int, weekOfYear: int): DateTime()
  + private static getNumberOfDay(day: string): int()
  + public static GetTarType(): string()
  + public static LateTarDates(): List<DateTime>()
  + public static NormalProtectionTarDates(): List<DateTime>()
  + public static NormalPossessionTarDates(): List<DateTime>()
  + public static ExtendedNormalPossessionTarDates(): List<DateTime>()
}

class ValidateUserRole {
  + public static CheckUserRole(roles: ArrayList): void()
  + public static IsNEL_Applicant(): Boolean()
  + public static IsDTL_Applicant(): Boolean()
  + public static IsNEL_ApplicantHOD(): Boolean()
  + public static IsDTL_ApplicantHOD(): Boolean()
  + public static IsNEL_PowerEndorser(): Boolean()
  + public static IsDTL_PowerEndorser(): Boolean()
  + public static IsNEL_PowerHOD(): Boolean()
  + public static IsDTL_TAPVerifier(): Boolean()
  + public static IsDTL_TAPApprover(): Boolean()
  + public static IsDTL_TAPHOD(): Boolean()
  + public static IsNEL_TAPVerifier(): Boolean()
  + public static IsNEL_TAPApprover(): Boolean()
  + public static IsNEL_TAPHOD(): Boolean()
  + public static IsDTL_TAR_SysAdmin(): Boolean()
  + public static IsNEL_TAR_SysAdmin(): Boolean()
  + public static IsNEL_PFR(): Boolean()
  + public static IsNEL_ChiefController(): Boolean()
  + public static IsNEL_TrafficController(): Boolean()
  + public static IsNEL_OCCScheduler(): Boolean()
  + public static IsDTL_PFR(): Boolean()
  + public static IsDTL_ChiefController(): Boolean()
  + public static IsDTL_TrafficController(): Boolean()
  + public static IsDTL_OCCScheduler(): Boolean()
}

class WeekRule {
  + public static FirstDateOfWeek(year: int, weekOfYear: int): DateTime()
}

class AnonymousSite {
  + protected Page_Load(sender: object, e: EventArgs): void()
}

AnonymousSite --|> System.Web.UI.MasterPage
class BundleConfig {
  + public static RegisterBundles(bundles: BundleCollection): void()
}

class RouteConfig {
  + public static RegisterRoutes(routes: RouteCollection): void()
}

class Basepage {
  + protected Page_Load(sender: object, e: System.EventArgs): void()
  + public GetSqlConnection(): SqlConnection()
  + protected GetSqlCommand(cmdStr: string): SqlCommand()
  + protected GetSqlDataAdapter(cmd: SqlCommand): SqlDataAdapter()
  + public static QuoteRemove(s: string): string()
}

Basepage --|> System.Web.UI.Page
class BasePage {
  
}

class DBAccess {
  + public ExecuteScalar(commandtext: string): object()
  + public ExecuteScalar(commandtext: string, values: SqlParameter []): object()
  + public ExecuteNonQuery(commandtext: string): object()
  + public ExecuteNonQuery(commandtext: string, values: SqlParameter[]): object()
  + public ExecuteDataSet(commandtext: string): DataSet()
  + public ExecuteDataSet(commandtext: string, values: SqlParameter[]): DataSet()
  + public Open(): void()
  + public Close(): void()
  + public Dispose(): void()
}

class oAppList {
  + public getAppListOnLoad(StrLine: string, StrToAccessDate: string, StrFromAccessDate: string, StrTARType: string, dsref: DataSet): void()
  + public getAppListMasterOnLoad(StrLine: string, StrTrackType: string, StrToAccessDate: string, StrFromAccessDate: string, StrTARType: string, dsref: DataSet): void()
  + public getAppListChildOnLoad(StrLine: string, StrTrackType: string, StrToAccessDate: string, StrFromAccessDate: string, StrTARType: string, IntSectorID: int, dsref: DataSet): void()
}

oAppList --|> Basepage
class oBlockDate {
  + public getBlockDateOnLoad(StrLine: string, StrTrackType: string, StrBlockDate: string, dsref: DataSet): void()
  + public saveBlockDate(StrLine: string, StrTrackType: string, StrBlockDate: string, StrBlockReason: string, StrUserLI: string, Errormsg: string): void()
  + public delBlockDate(IntBlockID: int, Errormsg: string): void()
}

oBlockDate --|> Basepage
class oCompany {
  + public static getCompInformationByID(CompanyID: string): DataSet()
  + public static geCompanyListByUENCompanyName(searchUEN: string, searchCompanyName: string): DataSet()
  + public static UpdateCompanyInformation(compID: int, name: string, businessOwnerName: string, companyOfficeNumber: string, mobileNumber: string, email: string, isActive: bool, updatedBy: int): int()
}

class oDepotAppList {
  + public getLocation(dsref: DataSet): void()
  + public getAppListOnLoad(StrLine: string, StrToAccessDate: string, StrFromAccessDate: string, StrTARType: string, dsref: DataSet): void()
  + public getAppListMasterOnLoad(StrLine: string, StrTrackType: string, StrToAccessDate: string, StrFromAccessDate: string, StrTARType: string, location: string, dsref: DataSet): void()
  + public getAppListChildOnLoad(StrLine: string, StrTrackType: string, StrToAccessDate: string, StrFromAccessDate: string, StrTARType: string, IntSectorID: int, location: string, dsref: DataSet): void()
}

oDepotAppList --|> Basepage
class oDepotForm {
  + public getFormOnLoad(StrLine: string, strTrackType: string, StrAccessDate: string, StrAccessType: string, StrSectors: string, StrPowerSelTxt: string, dsref: DataSet): void()
  + public saveTempAtt(IntTARId: int, IntTARAccReqID: int, StrFileName: string, StrFileType: string, ByteFileUpload: byte[], dsref: DataSet): void()
  + public deleteTempAtt(IntTARId: int, IntTARAccReqID: int, dsref: DataSet): void()
  + public saveAccessDetails(StrLine: string, strTrackType: string, strLocationCode: string, StrAccessDate: string, StrAccessTimeSlot: string, StrAccessType: string, StrTARType: string, StrCompany: string, StrDesignation: string, StrName: string, StrOfficeNo: string, StrMobileNo: string, StrEmail: string, StrAccessTimeFrom: string, StrAccessTimeTo: string, StrAccessLocation: string, BitNeutralGap: int, BitIsExclusive: int, StrDescOfWork: string, StrARRemark: string, BitInvolvePower: int, BitPowerOn: int, Bit13ASocket: int, BitCrossOver: int, StrUserID: string, ProtectionType: string, TARId: int, Errormsg: string): void()
  + public saveAccessReqs(StrLine: string, StrTrackType: string, StrLocationCode: string, StrSelAccessReqs: string, StrPowerSelVal: string, StrPowerSelTxt: string, StrARRemark: string, IntTARId: int, Errormsg: string): void()
  + public cancelTARApp(IntTARId: int, Errormsg: string): void()
  + public savePossession(TARId: int, StrSummary: string, StrWorkDesc: string, IntTypeOfWorkId: int, StrWorkWithinPossession: string, StrTakePossession: string, StrGiveUpPossession: string, StrRemarks: string, IntPowerOnOff: int, StrEngTrainFormation: string, StrEngTrainArriveLoc: string, StrEngTrainArriveTime: string, StrEngTrainDepartLoc: string, StrEngTrainDepartTime: string, StrPCNRIC: string, StrPCName: string, PossId: int, Errormsg: string): void()
  + public savePossessionLimit(StrTypeOfProtectionLimit: string, StrRedFlashingLampsLoc: string, IntPossID: int, Errormsg: string): void()
  + public savePossessionWorkingLimit(StrRedFlashingLampsLoc: string, IntPossID: int, Errormsg: string): void()
  + public savePossessioOtherProtection(StrOtherProtection: string, IntPossID: int, Errormsg: string, rfl: string): void()
  + public savePossessionSector(StrSector: string, Poweroff: int, IntNoOFSCD: int, StrBreakerOut: string, IntPossID: int, Errormsg: string): void()
  + public updateAccessDetails(StrCompany: string, StrDesignation: string, StrName: string, StrOfficeNo: string, StrMobileNo: string, StrEmail: string, StrAccessTimeFrom: string, StrAccessTimeTo: string, BitIsExclusive: int, StrDescOfWork: string, StrARRemark: string, BitInvolvePower: int, BitPowerOn: int, Bit13ASocket: int, BitCrossOver: int, StrUserID: string, ProtectionType: string, TARId: int, Errormsg: string): void()
  + public submitForm(StrLine: string, StrTrackType: string, StrAccessDate: string, StrAccessType: string, StrTARType: string, StrSectors: string, StrPowerSelVal: string, StrPowerSelTxt: string, IntIsExclusive: int, StrHOD: string, StrUserId: string, IntTARId: int, Errormsg: string, locationcode: string): void()
}

oDepotForm --|> Basepage
class oDepotFormApp {
  + public getFormAppOnLoad(StrTARID: string, StrLoginUser: string, dsref: DataSet): void()
  + public getAddBufferZone(StrTARID: string, dsref: DataSet): void()
  + public saveAddBufferZone(TARID: int, SectorID: int, Errormsg: string): void()
  + public saveDelBufferZone(TARID: int, SectorID: int, Errormsg: string): void()
  + public getAddTVF(StrTARID: string, dsref: DataSet): void()
  + public saveAddTVF(TARID: int, StationID: int, StrDir: string, Errormsg: string): void()
  + public saveDelTVF(TARID: int, TVFID: int, Errormsg: string): void()
  + public appEndorse(IntTARID: int, IntTARWFID: int, IntEID: int, IntELevel: int, StrRemarks: string, StrUserLI: string, StrTVFRunMode: string, StrTVFRunModeUpdInd: string, Errormsg: string): void()
  + public appReject(IntTARID: int, IntTARWFID: int, IntEID: int, IntELevel: int, StrRemarks: string, StrUserLI: string, Errormsg: string): void()
  + public appProceedToApp(IntTARID: int, IntTARWFID: int, IntEID: int, IntELevel: int, StrRemarks: string, StrUserLI: string, StrTVFRunMode: string, StrTVFRunModeUpdInd: string, Errormsg: string): void()
}

oDepotFormApp --|> Basepage
class oDepotInbox {
  + public getLocation(dsref: DataSet): void()
  + public getInboxOnLoad(StrLine: string, StrAccessDate: string, StrTARType: string, StrLoginUser: string, dsref: DataSet): void()
  + public getInboxMasterOnLoad(StrLine: string, StrTrackType: string, StrAccessDate: string, StrTARType: string, StrLoginUser: string, location: string, dsref: DataSet): void()
  + public getInboxChildOnLoad(StrLine: string, StrTrackType: string, StrAccessDate: string, StrTARType: string, StrLoginUser: string, IntSectorID: int, locationcode: string, dsref: DataSet): void()
}

oDepotInbox --|> Basepage
class oDepotSectorBooking {
  + public getSectorBookingOnLoad(StrLine: string, StrTrackType: string, StrAccessDate: string, StrTARType: string, StrAccessType: string, dsref: DataSet, StrLocation: string): void()
  + public chkNRICVal(StrNRIC: string, TrackType: string, StrQualDate: string, StrLine: string, dsref: DataSet): void()
  + public chkSpecialRule(StrAccessType: string, StrSectors: string, StrPowerSelTxt: string, dsref: DataSet): void()
  + public chkSubSet(StrD1Sel: string, StrD2Sel: string, dsref: DataSet): void()
}

oDepotSectorBooking --|> Basepage
class oDepotTarForn {
  + public getLocation(dsref: DataSet): void()
}

oDepotTarForn --|> Basepage
class EncryptionUtil {
  + public Encrypt(value: string): string()
  + public Decrypt(cipher: string): string()
}

class oForm {
  + public getFormOnLoad(StrLine: string, strTrackType: string, StrAccessDate: string, StrAccessType: string, StrSectors: string, StrPowerSelTxt: string, dsref: DataSet): void()
  + public saveTempAtt(IntTARId: int, IntTARAccReqID: int, StrFileName: string, StrFileType: string, ByteFileUpload: byte[], dsref: DataSet): void()
  + public deleteTempAtt(IntTARId: int, IntTARAccReqID: int, dsref: DataSet): void()
  + public saveAccessDetails(StrLine: string, strTrackType: string, StrAccessDate: string, StrAccessType: string, StrTARType: string, StrCompany: string, StrDesignation: string, StrName: string, StrOfficeNo: string, StrMobileNo: string, StrEmail: string, StrAccessTimeFrom: string, StrAccessTimeTo: string, StrAccessLocation: string, BitNeutralGap: int, BitIsExclusive: int, StrDescOfWork: string, StrARRemark: string, BitInvolvePower: int, BitPowerOn: int, Bit13ASocket: int, BitCrossOver: int, StrUserID: string, TARId: int, Errormsg: string): void()
  + public saveAccessReqs(StrLine: string, StrTrackType: string, StrSelAccessReqs: string, StrPowerSelVal: string, StrPowerSelTxt: string, StrARRemark: string, IntTARId: int, Errormsg: string): void()
  + public cancelTARApp(IntTARId: int, Errormsg: string): void()
  + public savePossession(TARId: int, StrSummary: string, StrWorkDesc: string, IntTypeOfWorkId: int, StrWorkWithinPossession: string, StrTakePossession: string, StrGiveUpPossession: string, StrRemarks: string, IntPowerOnOff: int, StrEngTrainFormation: string, StrEngTrainArriveLoc: string, StrEngTrainArriveTime: string, StrEngTrainDepartLoc: string, StrEngTrainDepartTime: string, StrPCNRIC: string, StrPCName: string, PossId: int, Errormsg: string): void()
  + public savePossessionLimit(StrTypeOfProtectionLimit: string, StrRedFlashingLampsLoc: string, IntPossID: int, Errormsg: string): void()
  + public savePossessionWorkingLimit(StrRedFlashingLampsLoc: string, IntPossID: int, Errormsg: string): void()
  + public savePossessioOtherProtection(StrOtherProtection: string, IntPossID: int, Errormsg: string): void()
  + public savePossessioPowerSector(StrPowerSector: string, IntNoOFSCD: int, StrBreakerOut: string, IntPossID: int, Errormsg: string): void()
  + public updateAccessDetails(StrCompany: string, StrDesignation: string, StrName: string, StrOfficeNo: string, StrMobileNo: string, StrEmail: string, StrAccessTimeFrom: string, StrAccessTimeTo: string, BitIsExclusive: int, StrDescOfWork: string, StrARRemark: string, BitInvolvePower: int, BitPowerOn: int, Bit13ASocket: int, BitCrossOver: int, StrUserID: string, TARId: int, Errormsg: string): void()
  + public submitForm(StrLine: string, StrTrackType: string, StrAccessDate: string, StrAccessType: string, StrTARType: string, StrSectors: string, StrPowerSelVal: string, StrPowerSelTxt: string, IntIsExclusive: int, StrHOD: string, StrUserId: string, IntTARId: int, Errormsg: string): void()
}

oForm --|> Basepage
class oFormApp {
  + public getFormAppOnLoad(StrTARID: string, StrLoginUser: string, dsref: DataSet): void()
  + public getAddBufferZone(StrTARID: string, dsref: DataSet): void()
  + public saveAddBufferZone(TARID: int, SectorID: int, Errormsg: string): void()
  + public saveDelBufferZone(TARID: int, SectorID: int, Errormsg: string): void()
  + public getAddTVF(StrTARID: string, dsref: DataSet): void()
  + public saveAddTVF(TARID: int, StationID: int, StrDir: string, Errormsg: string): void()
  + public saveDelTVF(TARID: int, TVFID: int, Errormsg: string): void()
  + public appEndorse(IntTARID: int, IntTARWFID: int, IntEID: int, IntELevel: int, StrRemarks: string, StrUserLI: string, StrTVFRunMode: string, StrTVFRunModeUpdInd: string, Errormsg: string): void()
  + public appReject(IntTARID: int, IntTARWFID: int, IntEID: int, IntELevel: int, StrRemarks: string, StrUserLI: string, Errormsg: string): void()
  + public appProceedToApp(IntTARID: int, IntTARWFID: int, IntEID: int, IntELevel: int, StrRemarks: string, StrUserLI: string, StrTVFRunMode: string, StrTVFRunModeUpdInd: string, Errormsg: string): void()
}

oFormApp --|> Basepage
class oInbox {
  + public getInboxOnLoad(StrLine: string, StrAccessDate: string, StrTARType: string, StrLoginUser: string, dsref: DataSet): void()
  + public getInboxMasterOnLoad(StrLine: string, StrTrackType: string, StrAccessDate: string, StrTARType: string, StrLoginUser: string, dsref: DataSet): void()
  + public getInboxChildOnLoad(StrLine: string, StrTrackType: string, StrAccessDate: string, StrTARType: string, StrLoginUser: string, IntSectorID: int, dsref: DataSet): void()
}

oInbox --|> Basepage
class LANUtil {
  + public IsAuthenticated(uname: string): bool()
  + public GetDisplayName(uname: string): string()
}

class oMenu {
  + public static getParentMenuByUserRole(userid: string): DataSet()
  + public static getChildMenuByUserRole(userid: string, mid: string): DataSet()
}

class oOPD {
  + public getOPD(StrLine: string, StrTrackType: string, dsref: DataSet): void()
}

oOPD --|> Basepage
class oPagePermission {
  + public getPagePermission(userid: string, @menuid: string, permission: bool): void()
}

oPagePermission --|> Basepage
class oParameter {
  + public static getParaValByParaCode(paraCode: string, paraValue1: string): DataSet()
}

class oRGS {
  + public getRGS(StrLine: string, StrTrackType: string, dsref: DataSet): void()
  + public getDepotRGS(StrLine: string, StrTrackType: string, dsref: DataSet, accessDate: DateTime?): void()
  + public ackReg(TARID: int, UserID: string, Errormsg: string): void()
  + public ackSMS(TARID: int, EncTARID: string, SMSType: string, Errormsg: string): void()
  + public ackSurrender(TARID: int, UserID: string, Errormsg: string, tracktype: string): void()
  + public grantTOA(TARID: int, EncTARID: string, UserID: string, Errormsg: string): void()
  + public grantDepotTOA(TARID: int, EncTARID: string, UserID: string, toaTiming: string, Errormsg: string): void()
  + public cancelTAR(TARID: int, CancelRemarks: string, UserID: string, Errormsg: string, tracktype: string): void()
  + public getUpdDets(TARID: int, dsref: DataSet): void()
  + public updDets(TARID: int, InchargeNRIC: string, MobileNo: string, TetraRadioNo: string, UserID: string, StrTrackType: string, Errormsg: string): void()
  + public updQTS(TARID: int, InchargeNRIC: string, UserID: string, Errormsg: string, QTSQCode: string, QTSLine: string, tracktype: string): void()
  + public getAckSMS(TARID: int, dsref: DataSet): void()
  + public getRGSEnq(StrLine: string, StrTrackType: string, StrOPDate: string, dsref: DataSet): void()
  + public getDepotRGSEnq(StrLine: string, StrTrackType: string, accessDate: DateTime?, dsref: DataSet): void()
  + public getSummaryReport(StrLine: string, StrTrackType: string, StrAccessDate: string, dsref: DataSet): void()
}

oRGS --|> Basepage
class oSectorBooking {
  + public getSectorBookingOnLoad(StrLine: string, StrTrackType: string, StrAccessDate: string, StrTARType: string, StrAccessType: string, dsref: DataSet): void()
  + public chkNRICVal(StrNRIC: string, TrackType: string, StrQualDate: string, StrLine: string, dsref: DataSet): void()
  + public chkSpecialRule(StrAccessType: string, StrSectors: string, StrPowerSelTxt: string, dsref: DataSet): void()
  + public chkSubSet(StrD1Sel: string, StrD2Sel: string, dsref: DataSet): void()
}

oSectorBooking --|> Basepage
class oTOAReg {
  + public getStationCode(StrLine: string, StrStationName: string, dsref: DataSet): void()
  + public regTOA(StrLine: string, StrTrackType: string, StrType: string, StrLoc: string, StrTARNo: string, StrNRIC: string, TOAID: int, Errormsg: string): void()
  + public onLoad(IntTOAID: int, dsref: DataSet): void()
  + public getTAREnquiryUsername(uid: string, line: string, TrackType: string, tarType: string, accessType: string, tarStatusId: string, accessDateFrom: string, accessDateTo: string, dsref: DataSet): void()
  + public getTAREnquiryDepartment(uid: string, line: string, TrackType: string, tarType: string, accessType: string, tarStatusId: string, accessDateFrom: string, accessDateTo: string, dsref: DataSet): void()
  + public getDepotTAREnquiryDepartment(uid: string, line: string, TrackType: string, tarType: string, accessType: string, tarStatusId: string, accessDateFrom: string, accessDateTo: string, dsref: DataSet): void()
  + public usersManual(dsref: DataSet): void()
  + public updDets(StrMobileNo: string, StrTetraRadioNo: string, StrUserID: string, TOAID: int, Errormsg: string): void()
  + public getParties(IntTOAID: int, dsref: DataSet): void()
  + public addParties(StrFIN: string, StrName: string, StrIsTMC: string, NoOfParties: int, TOAID: int, Errormsg: string): void()
  + public submitTOA(StrUserID: string, IntWitness: int, TOAID: int, Errormsg: string): void()
  + public deleteParties(IntPartiesID: int, TOAID: int, Errormsg: string): void()
  + public bookOutParties(IntPartiesID: int, TOAID: int, Errormsg: string): void()
  + public Surrender(TOAID: int, Errormsg: string): void()
  + public onLoadTOAURL(dsref: DataSet): void()
  + public updTOAURL(PLine: string, PLoc: string, PType: string, EncPLine: string, EncPLoc: string, EncPType: string, GenURL: string, Errormsg: string): void()
  + public getPointNo(IntTOAID: int, dsref: DataSet): void()
  + public removePointNo(pointid: int, TOAID: int, Errormsg: string): void()
  + public addPointNo(pointno: string, TOAID: int, createdBy: string, errormsg: string): void()
  + public saveProtectionType(protectiontype: string, TOAID: int, errormsg: string): void()
}

oTOAReg --|> Basepage
class oTrafficBulletin {
  + public getTBGenReport(StrLine: string, StrTrackType: string, StrFromAccessDate: string, StrToAccessDate: string, StrAccessType: string, dsref: DataSet): void()
  + public getTBGenSummary(StrLine: string, StrTracktype: string, StrFromAccessDate: string, StrToAccessDate: string, StrAccessType: string, dsref: DataSet): void()
}

oTrafficBulletin --|> Basepage
class oUser {
  + public static PasswordValidation(password: string): string()
  + public static checkUserExist(sapNo: string, loginID: string): DataSet()
  + public static getRailByUser(userId: string): DataSet()
  + public static getTrackTypeByLine(userId: string, uline: string): DataSet()
  + public static getRailByUserDepot(userId: string): DataSet()
  + public static getRolesByLineModule(line: string, tracktype: string, module: string): DataSet()
  + public static getAccessStatusByLoginID(loginID: string): DataSet()
  + public static getUserInfo(userId: string): DataSet()
  + public static getTrackType(loginID: string): DataSet()
  + public static getUserInformationByID(UserID: string): DataSet()
  + public static getUserInformationByLoginID(LoginID: string): DataSet()
  + public static getUserSignUpStatusByLoginID(LoginID: string): DataSet()
  + public static getExternal_UserInformationByLoginIDPWD(LoginID: string, LoginPWD: string): DataSet()
  + public static getUserAccessRoleInformationByID(UserID: string): DataSet()
  + public static getAllRoles(isExternal: int): DataSet()
  + public static getUserListByLoginUserID(userId: string, searchRail: string, searchUserType: string, searchActive: string, searchModule: string, searchUserID: string, searchUserName: string): DataSet()
  + public static sendPasswordResetLink(userID: string, cipher: string): int()
  + public static UpdateExternal_Password(userID: int, password: string): int()
  + public static UpdateUserInformation(userID: int, name: string, email: string, mobile: string, officeTel: string, dept: string, validTo: string, isActive: bool, updatedBy: int): int()
  + public static UpdateExternal_UserInformation(userID: int, name: string, dept: string, officeTel: string, mobile: string, email: string, sbstContactPersonName: string, sbstContactPersonDept: string, sbstContactPersonOffTel: string, validTo: string, isActive: bool, updatedBy: int): int()
  + public static DeleteUserRoleByUserID(userID: int): int()
  + public static UpdateUserRoleByUserRailModule(userID: int, rail: string, tracktype: string, locationcode: string, module: string, roles: List<int>, updatedBy: int): int()
  + public static UpdateUserQueryDept(userID: int, dt_dept: DataTable, updatedBy: int): int()
  + public static InsertInternalUserRegistration(sapNo: string, name: string, userName: string, email: string, mobile: string, officeNo: string, dept: string, validTo: string, purpose: string, access: DataTable): int()
  + public static InsertExternalUserRegistration(UENNo: string, company: string, name: string, email: string, dept: string, officeNo: string, mobile: string, sbstCPName: string, sbstCPDept: string, sbstCPOfficeNo: string, validTo: string, purpose: string, loginID: string, password: string, access: DataTable): int()
}

class oUserRegistration {
  + public static getRegistrationInboxByUserID(userId: int): DataSet()
  + public static getUserRegistrationInformationByRegModuleID(regModuleID: int): DataSet()
  + public static getUserRegistrationCompanyDetailsByRegID(regID: int): DataSet()
  + public static sendSignUpStatusLink(loginID: string, cipher: string): int()
  + public static checkUserDetailViewStatusRequestValidity(loginID: string, mode: string): DataSet()
  + public static checkUserRegistrationValidity(loginID: string): DataSet()
  + public static sendCompanyRegistrationLink(regID: string, cipher: string): int()
  + public static rejectUserRegistrationRequest(regModID: int, updatedBy: int): int()
  + public static UpdateApplicantCompanyRegistration(regID: int, company: string, uenNo: string, bizOwner: string, officeTel: string, mobile: string, email: string): int()
  + public static UpdateSystemAdminCompanyApprove(userID: int, modRegID: int): int()
  + public static UpdateSystemAdminApprove(userID: int, regModID: int, dt_roles: DataTable, dt_dept: DataTable): int()
  + public static UpdateSystemOwnerApprove(userID: int, regModID: int, dt_roles: DataTable, dt_dept: DataTable): int()
}

class _Default {
  + protected Page_Load(sender: object, e: EventArgs): void()
}

_Default --|> Page
class DepotTARApplication {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private BindLocation(): void()
  + private BindGrid(): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
  + private displayDates(TarType: string, dates: List<DateTime>, AccessType: string, Line: string, location: string): void()
  + private showHideControls(toggle: Boolean): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv1_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv2_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv3_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv4_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv5_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv6_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv7_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + private displayLegend(): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected rbPossession_CheckedChanged(sender: object, e: EventArgs): void()
  + protected rbProtection_CheckedChanged(sender: object, e: EventArgs): void()
}

DepotTARApplication --|> System.Web.UI.Page
class DepotTARAppList {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private BindLocation(): void()
  + protected lbSubmit_Click(sender: object, e: EventArgs): void()
  + private displayLegend(): void()
  + protected gvDir1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected lnkD1StrTARNo_Click(sender: object, e: EventArgs): void()
  + protected lbBack_Click(sender: object, e: EventArgs): void()
  + protected gvDir1Child_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
}

DepotTARAppList --|> System.Web.UI.Page
class DepotTAREnquiry {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected bindGrid(indicator: int): void()
  + private populateTarStatus(line: string): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected GridView1_PageIndexChanging(sender: object, e: GridViewPageEventArgs): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
  + protected btnReset_Click(sender: object, e: EventArgs): void()
  + protected btnPrint_Click(sender: object, e: EventArgs): void()
  + protected GridView1_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected GridView1_RowDeleting(sender: object, e: GridViewDeleteEventArgs): void()
  + protected btnWithdrawTARConfirm_Click(sender: object, e: EventArgs): void()
}

DepotTAREnquiry --|> System.Web.UI.Page
class DepotTAREnquiry_Detail {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected gvOperationReq_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPowerReq_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossPowerSector_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected lvTarApproval_ItemDataBound(sender: object, e: ListViewItemEventArgs): void()
  + protected Button1_Click(sender: object, e: EventArgs): void()
}

DepotTAREnquiry_Detail --|> System.Web.UI.Page
class DepotTAREnquiry_Print {
  + protected Page_Load(sender: object, e: EventArgs): void()
}

DepotTAREnquiry_Print --|> System.Web.UI.Page
class DepotTARForm {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected Tab1_Click(sender: object, e: EventArgs): void()
  + protected Tab2_Click(sender: object, e: EventArgs): void()
  + protected Tab3_Click(sender: object, e: EventArgs): void()
  + private PopOnLoad(): void()
  + protected chkOR_CheckedChanged(sender: object, e: EventArgs): void()
  + protected dgOR_ItemDataBound(sender: object, e: DataGridItemEventArgs): void()
  + protected btnUploadOR_Click(sender: object, e: EventArgs): void()
  + protected lnkDelete_Click(sender: object, e: EventArgs): void()
  + protected lnkDownload_Click(sender: object, e: EventArgs): void()
  + protected lbtnPossAPLAdd_Click(sender: object, e: EventArgs): void()
  + protected lbtnPossWLAdd_Click(sender: object, e: EventArgs): void()
  + protected lbtnPossOPAdd_Click(sender: object, e: EventArgs): void()
  + protected gvPossAddPL_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddPL_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected gvPossAddWL_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddWL_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected gvPossAddOO_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddOO_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected ddlDeptComp_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected lbCancelV1_Click(sender: object, e: EventArgs): void()
  + protected lbNextV1_Click(sender: object, e: EventArgs): void()
  + protected lbCancelV2_Click(sender: object, e: EventArgs): void()
  + protected lbNextV2_Click(sender: object, e: EventArgs): void()
  + protected lbCancelV3_Click(sender: object, e: EventArgs): void()
  + protected lbNextV3_Click(sender: object, e: EventArgs): void()
  + protected lbSubmitV2_Click(sender: object, e: EventArgs): void()
  + protected dgPossPowerSector_ItemDataBound(sender: object, e: DataGridItemEventArgs): void()
  + protected ddlBreakersOut_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + private valAccDets(): bool()
  + protected rdProtectionType_onSelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected ddlTimeslot_SelectedIndexChanged(sender: object, e: EventArgs): void()
}

DepotTARForm --|> System.Web.UI.Page
class DepotTARForm_App {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected Tab1_Click(sender: object, e: EventArgs): void()
  + protected Tab2_Click(sender: object, e: EventArgs): void()
  + protected Tab3_Click(sender: object, e: EventArgs): void()
  + private PopOnLoad(): void()
  + protected lnkDownload_Click(sender: object, e: EventArgs): void()
  + protected dgOR_ItemDataBound(sender: object, e: DataGridItemEventArgs): void()
  + protected gvPossAddPL_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddWL_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddOO_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected dgPossPowerSector_ItemDataBound(sender: object, e: DataGridItemEventArgs): void()
  + protected lbtnAddBufferZone_Click(sender: object, e: EventArgs): void()
  + protected gvAddBufferZone_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvAddBufferZone_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected lbCReject_Click(sender: object, e: EventArgs): void()
  + protected lbProcToApp_Click(sender: object, e: EventArgs): void()
  + protected lbNReject_Click(sender: object, e: EventArgs): void()
  + protected lbEndorse_Click(sender: object, e: EventArgs): void()
  + protected lbtnTARID_Click(sender: object, e: EventArgs): void()
  + protected gvConflictTAR_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
}

DepotTARForm_App --|> System.Web.UI.Page
class DepotTARInbox {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private BindLocation(): void()
  + protected lbSubmit_Click(sender: object, e: EventArgs): void()
  + protected lnkD1StrTARNo_Click(sender: object, e: EventArgs): void()
  + protected lnkD2StrTARNo_Click(sender: object, e: EventArgs): void()
  + protected lbAppList_Click(sender: object, e: EventArgs): void()
  + protected gvDir1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
}

DepotTARInbox --|> System.Web.UI.Page
class DepotTARSectorBooking {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private PopOnLoad(): void()
  + protected lbSubmit_Click(sender: object, e: EventArgs): void()
  + protected RBLPowerReq_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected cbDir1All_CheckedChanged(sender: object, e: EventArgs): void()
  + protected gvDir1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected lbAppList_Click(sender: object, e: EventArgs): void()
  + protected lbBack_Click(sender: object, e: EventArgs): void()
  + protected lbDiagram_Click(sender: object, e: EventArgs): void()
  + protected chkSel_CheckedChanged(sender: object, e: EventArgs): void()
}

DepotTARSectorBooking --|> System.Web.UI.Page
class DTCAuth {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + public SessionExpire(sender: object, e: EventArgs): void()
  + public GenerateToken(): string()
}

DTCAuth --|> System.Web.UI.Page
class ExternalLogin {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected btnLogin_Click(sender: object, e: EventArgs): void()
  + private CheckAccess(): void()
  + protected linkB_forgetPassword_Click(sender: object, e: EventArgs): void()
}

ExternalLogin --|> System.Web.UI.Page
class GenQRCode {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected btnGen_Click(sender: object, e: EventArgs): void()
}

GenQRCode --|> System.Web.UI.Page
class Global {
  + Application_Start(sender: object, e: EventArgs): void()
}

Global --|> HttpApplication
class ApiResponse {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected btnLogin_Click(sender: object, e: EventArgs): void()
  + private InternalLoginCheck(): void()
  + private CheckAccess(): void()
  + public GenerateToken(): string()
  + public CheckLANAuthentication(userID: string, userPwd: string, bearerToken: string): string()
  + public Encrypt(val: String): String()
}

class Login {
  
}

Login --|> System.Web.UI.Page
class Logout {
  + protected Page_Load(sender: object, e: EventArgs): void()
}

Logout --|> System.Web.UI.Page
class OCC_HoursAuthorisation {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private BindGrid(): void()
  + protected LoadOCCAuthCtrl_DTL(uID: string): void()
  + protected LoadOCCAuthCtrl_NEL(uID: string, dutyRosterCode: string): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected GridView1_RowCreated(sender: object, e: GridViewRowEventArgs): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected btnPreview_Click(sender: object, e: EventArgs): void()
}

OCC_HoursAuthorisation --|> System.Web.UI.Page
class OCC_HoursAuthorisation_Preview {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private BindGrid(): void()
  + protected LoadDutyRoster_Ctrl(uID: string): void()
  + protected LoadOCCAuthPreviewCtrl_DTL(): void()
  + protected LoadOCCAuthPreviewCtrl_NEL(): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected btnSearchOCC_Preview_Click(sender: object, e: EventArgs): void()
  + protected btnBackToOCCAuth_Click(sender: object, e: EventArgs): void()
}

OCC_HoursAuthorisation_Preview --|> System.Web.UI.Page
class OCCSearch_Roster {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected bindSearchCriteria(): void()
  + protected bindFirstShift(): void()
  + protected bindSecondShift(): void()
  + protected bindThirdShift(): void()
  + protected btnSearchRoster_Click(sender: object, e: EventArgs): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected ddlTrack_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected btnRefresh_Click(sender: object, e: EventArgs): void()
  + protected gvFirstShift_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvSecondShift_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvThirdShift_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
}

OCCSearch_Roster --|> System.Web.UI.Page
class OCCUpdate_Roster {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected bindSearchCriteria(): void()
  + private loadTrackType(): void()
  + protected bindFirstShift(): void()
  + protected bindSecondShift(): void()
  + protected bindThirdShift(): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected ddlTrack_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected gvFirstShift_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvSecondShift_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvThirdShift_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected btnUpdateRoster_Click(sender: object, e: EventArgs): void()
  + protected btnRefresh_Click(sender: object, e: EventArgs): void()
}

OCCUpdate_Roster --|> System.Web.UI.Page
class OPD {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private PopOnLoad(): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected lbRefresh_Click(sender: object, e: EventArgs): void()
}

OPD --|> System.Web.UI.Page
class RGS {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private PopOnLoad(): void()
  + protected gvRGS_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvRGS_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected lbRefresh_Click(sender: object, e: EventArgs): void()
  + protected lbCancelTOA_Click(sender: object, e: EventArgs): void()
  + protected ddlUpdTARID_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected lbUpdDets_Click(sender: object, e: EventArgs): void()
  + protected updQTS(StrNRIC: string, StrQcode: string, StrRail: string, StrUserID: string): string()
  + public static ToDecode(inputstring: string): string()
  + public static ToEncode(inputstring: string): string()
  + protected Timer_Tick(sender: object, e: EventArgs): void()
  + protected lbGrantTOADepot_Click(sender: object, e: EventArgs): void()
}

RGS --|> System.Web.UI.Page
class RGSAckSMS {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected lbAck_Click(sender: object, e: EventArgs): void()
  + protected lblComplete_Click(sender: object, e: EventArgs): void()
  + private PopOnLoad(): void()
  + public static ToDecode(inputstring: string): string()
  + public static ToEncode(inputstring: string): string()
}

RGSAckSMS --|> System.Web.UI.Page
class RGSEnquiry {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private loadDepotControl(): void()
  + private PopOnLoad(): void()
  + protected gvRGS_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected ddlTrack_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected lbRefresh_Click(sender: object, e: EventArgs): void()
  + protected gvRGS_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected lbPrint_Click(sender: object, e: EventArgs): void()
}

RGSEnquiry --|> System.Web.UI.Page
class RGSPrint {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected gvRGS_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvRGS_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
}

RGSPrint --|> System.Web.UI.Page
class SiteMaster {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected linkB_viewProfile_Click(sender: object, e: EventArgs): void()
  + protected linkB_logout_Click(sender: object, e: EventArgs): void()
  + protected linkB_signUpNewSystem_Click(sender: object, e: EventArgs): void()
}

SiteMaster --|> MasterPage
class Site_Mobile {
  + protected Page_Load(sender: object, e: EventArgs): void()
}

Site_Mobile --|> System.Web.UI.MasterPage
class SummaryReport {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected lbSearch_Click(sender: object, e: EventArgs): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + private PopOnLoad(): void()
}

SummaryReport --|> System.Web.UI.Page
class TARApplication {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private BindGrid(): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
  + private displayDates(TarType: string, dates: List<DateTime>, AccessType: string, Line: string): void()
  + private showHideControls(toggle: Boolean): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv1_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv1_B2_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv2_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv2_B2_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv3_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv3_B2_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv4_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv4_B2_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv5_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv5_B2_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv6_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv6_B2_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv7_B1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gv7_B2_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + private displayLegend(): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected rbPossession_CheckedChanged(sender: object, e: EventArgs): void()
  + protected rbProtection_CheckedChanged(sender: object, e: EventArgs): void()
}

TARApplication --|> System.Web.UI.Page
class TARAppList {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected lbSubmit_Click(sender: object, e: EventArgs): void()
  + private displayLegend(): void()
  + protected gvDir2_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvDir1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected lnkD2StrTARNo_Click(sender: object, e: EventArgs): void()
  + protected lnkD1StrTARNo_Click(sender: object, e: EventArgs): void()
  + protected lbBack_Click(sender: object, e: EventArgs): void()
  + protected gvDir2Child_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvDir1Child_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
}

TARAppList --|> System.Web.UI.Page
class TARBlockDate {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private ReloadRecs(): void()
  + protected gvBlockDate_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvBlockDate_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected lbSearch_Click(sender: object, e: EventArgs): void()
  + protected lbNew_Click(sender: object, e: EventArgs): void()
  + protected ddlRail_SelectedIndexChanged(sender: object, e: EventArgs): void()
}

TARBlockDate --|> System.Web.UI.Page
class TARBlockDate_Add {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected lbtnAddBlockDate_Click(sender: object, e: EventArgs): void()
  + protected lbtnAddCancel_Click(sender: object, e: EventArgs): void()
}

TARBlockDate_Add --|> System.Web.UI.Page
class TAREnquiry {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected bindGrid(indicator: int): void()
  + private populateTarStatus(line: string): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected GridView1_PageIndexChanging(sender: object, e: GridViewPageEventArgs): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
  + protected btnReset_Click(sender: object, e: EventArgs): void()
  + protected btnPrint_Click(sender: object, e: EventArgs): void()
  + protected GridView1_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected GridView1_RowDeleting(sender: object, e: GridViewDeleteEventArgs): void()
  + protected btnWithdrawTARConfirm_Click(sender: object, e: EventArgs): void()
}

TAREnquiry --|> System.Web.UI.Page
class TAREnquiry_Detail {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected BindPossessionLimit(): void()
  + protected gvOperationReq_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPowerReq_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossPowerSector_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected lvTarApproval_ItemDataBound(sender: object, e: ListViewItemEventArgs): void()
  + protected Button1_Click(sender: object, e: EventArgs): void()
  + protected gvPossLimit_PageIndexChanging(sender: object, e: GridViewPageEventArgs): void()
}

TAREnquiry_Detail --|> System.Web.UI.Page
class TAREnquiry_Print {
  + protected Page_Load(sender: object, e: EventArgs): void()
}

TAREnquiry_Print --|> System.Web.UI.Page
class TARForm {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected Tab1_Click(sender: object, e: EventArgs): void()
  + protected Tab2_Click(sender: object, e: EventArgs): void()
  + protected Tab3_Click(sender: object, e: EventArgs): void()
  + private PopOnLoad(): void()
  + protected chkOR_CheckedChanged(sender: object, e: EventArgs): void()
  + protected dgOR_ItemDataBound(sender: object, e: DataGridItemEventArgs): void()
  + protected btnUploadOR_Click(sender: object, e: EventArgs): void()
  + protected lnkDelete_Click(sender: object, e: EventArgs): void()
  + protected lnkDownload_Click(sender: object, e: EventArgs): void()
  + protected lbtnPossAPLAdd_Click(sender: object, e: EventArgs): void()
  + protected lbtnPossWLAdd_Click(sender: object, e: EventArgs): void()
  + protected lbtnPossOPAdd_Click(sender: object, e: EventArgs): void()
  + protected gvPossAddPL_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddPL_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected gvPossAddWL_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddWL_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected gvPossAddOO_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddOO_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected ddlDeptComp_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected lbCancelV1_Click(sender: object, e: EventArgs): void()
  + protected lbNextV1_Click(sender: object, e: EventArgs): void()
  + protected lbCancelV2_Click(sender: object, e: EventArgs): void()
  + protected lbNextV2_Click(sender: object, e: EventArgs): void()
  + protected lbCancelV3_Click(sender: object, e: EventArgs): void()
  + protected lbNextV3_Click(sender: object, e: EventArgs): void()
  + protected lbSubmitV2_Click(sender: object, e: EventArgs): void()
  + protected dgPossPowerSector_ItemDataBound(sender: object, e: DataGridItemEventArgs): void()
  + protected ddlBreakersOut_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + private valAccDets(): bool()
}

TARForm --|> System.Web.UI.Page
class TARForm_App {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected Tab1_Click(sender: object, e: EventArgs): void()
  + protected Tab2_Click(sender: object, e: EventArgs): void()
  + protected Tab3_Click(sender: object, e: EventArgs): void()
  + private PopOnLoad(): void()
  + protected lnkDownload_Click(sender: object, e: EventArgs): void()
  + protected dgOR_ItemDataBound(sender: object, e: DataGridItemEventArgs): void()
  + protected gvPossAddPL_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddWL_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddOO_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected dgPossPowerSector_ItemDataBound(sender: object, e: DataGridItemEventArgs): void()
  + protected lbtnAddBufferZone_Click(sender: object, e: EventArgs): void()
  + protected gvAddBufferZone_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvAddBufferZone_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected lbtnAddTVFStation_Click(sender: object, e: EventArgs): void()
  + protected gvAddTVF_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvAddTVF_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected lbCReject_Click(sender: object, e: EventArgs): void()
  + protected lbProcToApp_Click(sender: object, e: EventArgs): void()
  + protected lbNReject_Click(sender: object, e: EventArgs): void()
  + protected lbEndorse_Click(sender: object, e: EventArgs): void()
  + protected lbtnTARID_Click(sender: object, e: EventArgs): void()
  + protected gvConflictTAR_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected rblTVFRunMode_SelectedIndexChanged(sender: object, e: EventArgs): void()
}

TARForm_App --|> System.Web.UI.Page
class TARInbox {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected lbSubmit_Click(sender: object, e: EventArgs): void()
  + protected lnkD1StrTARNo_Click(sender: object, e: EventArgs): void()
  + protected lnkD2StrTARNo_Click(sender: object, e: EventArgs): void()
  + protected lbAppList_Click(sender: object, e: EventArgs): void()
  + protected gvDir1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvDir2_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
}

TARInbox --|> System.Web.UI.Page
class TARSectorBooking {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private PopOnLoad(): void()
  + protected lbSubmit_Click(sender: object, e: EventArgs): void()
  + private ChkSeq(SelSec: string): bool()
  + protected RBLPowerReq_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected cbDir1All_CheckedChanged(sender: object, e: EventArgs): void()
  + protected cbDir2All_CheckedChanged(sender: object, e: EventArgs): void()
  + protected gvDir1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvDir2_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected lbAppList_Click(sender: object, e: EventArgs): void()
  + protected lbBack_Click(sender: object, e: EventArgs): void()
}

TARSectorBooking --|> System.Web.UI.Page
class TARViewDetails {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private PopOnLoad(): void()
  + protected dgOR_ItemDataBound(sender: object, e: DataGridItemEventArgs): void()
  + protected gvPossAddPL_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddWL_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvPossAddOO_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected dgPossPowerSector_ItemDataBound(sender: object, e: DataGridItemEventArgs): void()
  + protected lbBack_Click(sender: object, e: EventArgs): void()
}

TARViewDetails --|> System.Web.UI.Page
class Test {
  + protected Page_Load(sender: object, e: EventArgs): void()
}

Test --|> System.Web.UI.Page
class TOA {
  + protected Page_Load(sender: object, e: EventArgs): void()
}

TOA --|> System.Web.UI.MasterPage
class TOAAddParties {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected bindPoints(toaid: int): void()
  + protected lbNextV1_Click(sender: object, e: EventArgs): void()
  + protected Tab1_Click(sender: object, e: EventArgs): void()
  + protected Tab2_Click(sender: object, e: EventArgs): void()
  + protected lbPrevV2_Click(sender: object, e: EventArgs): void()
  + protected lbAddParties_Click(sender: object, e: EventArgs): void()
  + protected gvParties_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvParties_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + public static LogError(ex: string): void()
}

TOAAddParties --|> System.Web.UI.Page
class TOAApplication {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected lbtnSubmit_Click(sender: object, e: EventArgs): void()
  + public static ToDecode(inputstring: string): string()
  + public static ToEncode(inputstring: string): string()
  + protected getLoginResponse(uid: string, password: string): string()
  + public static LogError(ex: string): void()
}

TOAApplication --|> System.Web.UI.Page
class TOABookIn {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected loadProtectionType(): void()
  + protected BindWitness(dt1: DataSet): void()
  + protected Tab1_Click(sender: object, e: EventArgs): void()
  + protected Tab2_Click(sender: object, e: EventArgs): void()
  + protected Tab3_Click(sender: object, e: EventArgs): void()
  + protected lbNextV1_Click(sender: object, e: EventArgs): void()
  + protected lbNextV2_Click(sender: object, e: EventArgs): void()
  + protected lbPrevV2_Click(sender: object, e: EventArgs): void()
  + protected lbPrevV3_Click(sender: object, e: EventArgs): void()
  + protected lbSubmit_Click(sender: object, e: EventArgs): void()
  + protected gvParties_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvParties_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected lbAddParties_Click(sender: object, e: EventArgs): void()
  + public static LogError(ex: string): void()
  + protected saveProtectionType(): void()
  + protected BtnAddProt_Click(sender: object, e: EventArgs): void()
  + protected bindPoints(toaid: int): void()
  + protected GVProtectionType_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected rBtnProtectionList_SelectedIndexChanged(sender: object, e: EventArgs): void()
}

TOABookIn --|> System.Web.UI.Page
class TOABookOut {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected lbNextV1_Click(sender: object, e: EventArgs): void()
  + protected Tab1_Click(sender: object, e: EventArgs): void()
  + protected Tab2_Click(sender: object, e: EventArgs): void()
  + protected lbPrevV2_Click(sender: object, e: EventArgs): void()
  + protected lbAddParties_Click(sender: object, e: EventArgs): void()
  + protected gvParties_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvParties_RowCommand(sender: object, e: GridViewCommandEventArgs): void()
  + protected lbSurrender_Click(sender: object, e: EventArgs): void()
  + public static LogError(ex: string): void()
}

TOABookOut --|> System.Web.UI.Page
class TOAError {
  + protected Page_Load(sender: object, e: EventArgs): void()
}

TOAError --|> System.Web.UI.Page
class TOAGenURL {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected lblGen_Click(sender: object, e: EventArgs): void()
  + public static ToDecode(inputstring: string): string()
  + public static ToEncode(inputstring: string): string()
}

TOAGenURL --|> System.Web.UI.Page
class TrafficBulletin {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected btnGeneratePossessionReport_Click(sender: object, e: EventArgs): void()
  + private GenerateReportInPDF(possessionTars: List<Tar>): void()
  + private getPDFPageLoadDataTAR(tar: Tar): PdfPTable()
  + private exportPDF(dTable: PdfPTable): void()
  + protected ddlLine_SelectedIndexChanged(sender: object, e: EventArgs): void()
  + protected btnGenerateSummaryReport_Click(sender: object, e: EventArgs): void()
  + protected btnGenerateReport_Click(sender: object, e: EventArgs): void()
}

TrafficBulletin --|> System.Web.UI.Page
class TVFAcknowledgement {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private BindGrid(): void()
  + protected LoadOCCTVF_AckCtrl(uID: string): void()
}

TVFAcknowledgement --|> System.Web.UI.Page
class TVFAcknowledgement_Enquiry {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private BindGrid(): void()
  + protected LoadOCCTVF_AckCtrl(uID: string): void()
  + protected btnSearch_Click(sender: object, e: EventArgs): void()
}

TVFAcknowledgement_Enquiry --|> System.Web.UI.Page
class menu {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected Generate_Menu(userid: string, isInternet: string): void()
  + protected Generate_Menu2(userid: string): void()
}

menu --|> System.Web.UI.UserControl
class OCCAuth_NEL {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected populateOCCAuth(): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
}

OCCAuth_NEL --|> System.Web.UI.UserControl
class OCCAuth_NEL_bak {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected populateOCCAuth(): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
}

OCCAuth_NEL_bak --|> System.Web.UI.UserControl
class OCCAuthCC_DTL {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected populateOCCAuth(): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
}

OCCAuthCC_DTL --|> System.Web.UI.UserControl
class OCCAuthPFR_DTL {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected populateOCCAuth(): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
}

OCCAuthPFR_DTL --|> System.Web.UI.UserControl
class OCCAuthPreview {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private populateOCCAuthPreview(): void()
  + private ShowingGroupingDataInGridView(gridViewRows: GridViewRowCollection, startIndex: int, totalColumns: int): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected GridView1_RowCreated(sender: object, e: GridViewRowEventArgs): void()
}

OCCAuthPreview --|> System.Web.UI.UserControl
class OCCAuthPreview_NEL {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private populateOCCAuthPreview(): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected GridView1_RowCreated(sender: object, e: GridViewRowEventArgs): void()
}

OCCAuthPreview_NEL --|> System.Web.UI.UserControl
class OCCAuthPreview_Roster {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected bindFirstShift(): void()
  + protected bindSecondShift(): void()
  + protected bindThirdShift(): void()
  + protected searchDutyRoster(): void()
  + protected gvFirstShift_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvSecondShift_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected gvThirdShift_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
}

OCCAuthPreview_Roster --|> System.Web.UI.UserControl
class OCCAuthTC_DTL {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected populateOCCAuth(): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
}

OCCAuthTC_DTL --|> System.Web.UI.UserControl
class OCCTVF_Ack {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected populateOCCTVF_Ack(): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
  + protected btnReject_Click(sender: object, e: EventArgs): void()
  + protected ShowRemark(sender: object, e: EventArgs): void()
  + protected btnSave_Click(sender: object, e: EventArgs): void()
  + protected ShowTarTVF(sender: object, e: EventArgs): void()
}

OCCTVF_Ack --|> System.Web.UI.UserControl
class OCCTVF_Ack_Preview {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected populateOCCTVF_Ack(): void()
  + protected GridView1_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected btnSubmit_Click(sender: object, e: EventArgs): void()
  + protected btnReject_Click(sender: object, e: EventArgs): void()
  + protected ShowRemark(sender: object, e: EventArgs): void()
  + protected btnSave_Click(sender: object, e: EventArgs): void()
  + protected ShowTarTVF(sender: object, e: EventArgs): void()
}

OCCTVF_Ack_Preview --|> System.Web.UI.UserControl
class UserDetailViewFrmEmail {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private buildDummySystemSelectiondata(): DataTable()
}

UserDetailViewFrmEmail --|> System.Web.UI.Page
class AddCompany {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private setupPage(UserRegID: int): void()
  + protected btn_externalSave_Click(sender: object, e: EventArgs): void()
  + protected btn_externalCancel_Click(sender: object, e: EventArgs): void()
}

AddCompany --|> System.Web.UI.Page
class MaintainCompany {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private SetupPage(): void()
  + private EncryptID(ds: DataSet): DataSet()
  + private buildDummySystemSelectiondata(): DataTable()
  + protected btn_search_Click(sender: object, e: EventArgs): void()
  + protected btn_clear_Click(sender: object, e: EventArgs): void()
}

MaintainCompany --|> System.Web.UI.Page
class MaintainCompanyDetails {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private setupPage(companyID: int): void()
  + protected btn_updateCompany_Click(sender: object, e: EventArgs): void()
  + protected btn_back_Click(sender: object, e: EventArgs): void()
}

MaintainCompanyDetails --|> System.Web.UI.Page
class MaintainUser {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private SetupPage(): void()
  + protected btn_clear_Click(sender: object, e: EventArgs): void()
  + protected btn_search_Click(sender: object, e: EventArgs): void()
  + private EncryptID(ds: DataSet): DataSet()
}

MaintainUser --|> System.Web.UI.Page
class MaintainUserDetails {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private setupPage(userID: int): void()
  + protected btn_updateUser_Click(sender: object, e: EventArgs): void()
  + protected btn_back_Click(sender: object, e: EventArgs): void()
}

MaintainUserDetails --|> System.Web.UI.Page
class NewUserSignUp {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private ResetPage(): void()
  + private SetupPage(isExternal: bool): void()
  + private buildSystemSelectiondata(isExternal: bool): DataTable()
  + protected btn_internalNewSave_Click(sender: object, e: EventArgs): void()
  + protected btn_internalNewCancel_Click(sender: object, e: EventArgs): void()
  + protected btn_externalSave_Click(sender: object, e: EventArgs): void()
  + protected btn_externalCancel_Click(sender: object, e: EventArgs): void()
}

NewUserSignUp --|> System.Web.UI.Page
class RegistrationInbox {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private SetupPage(_userID: int): void()
  + private EncryptID(ds: DataSet): DataSet()
}

RegistrationInbox --|> System.Web.UI.Page
class RegistrationRequest {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private SetupPage(regModID: int): void()
  + private BuildPage(_dummy: UserRegistration): void()
  + private ResetPage(): void()
  + private buildDummySystemSelectiondata(): List<UserRegistration>()
  + protected btn_back_Click(sender: object, e: EventArgs): void()
  + protected cb_gvSysAdminRole_CheckedChanged(sender: object, e: EventArgs): void()
  + protected btn_assignAccess_Click(sender: object, e: EventArgs): void()
  + protected btn_rejectRequest_Click(sender: object, e: EventArgs): void()
  + protected btn_approvalUpdate_Click(sender: object, e: EventArgs): void()
  + protected btn_approvalReject_Click(sender: object, e: EventArgs): void()
  + protected cb_gvSysOwnerRole_CheckedChanged(sender: object, e: EventArgs): void()
  + protected btn_approveCompany_Click(sender: object, e: EventArgs): void()
  + protected btn_rejectCompany_Click(sender: object, e: EventArgs): void()
  + protected btn_resendLink_Click(sender: object, e: EventArgs): void()
  + protected btn_deleteRequest_Click(sender: object, e: EventArgs): void()
}

RegistrationRequest --|> System.Web.UI.Page
class ResetPassword {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private setupPage(UserRegID: int): void()
  + protected btn_externalSave_Click(sender: object, e: EventArgs): void()
  + protected btn_externalCancel_Click(sender: object, e: EventArgs): void()
}

ResetPassword --|> System.Web.UI.Page
class SignUpNewSystem {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private SetupPage(): void()
  + private ResetPage(): void()
  + private buildSystemSelectiondata(isExternal: bool): DataTable()
  + private UpdateGVRows(dr: DataRow, isExternal: bool): void()
  + protected gv_internalNewSystem_RowDataBound(sender: object, e: GridViewRowEventArgs): void()
  + protected btn_externalNext_Click(sender: object, e: EventArgs): void()
  + protected btn_internalNewSave_Click(sender: object, e: EventArgs): void()
}

SignUpNewSystem --|> System.Web.UI.Page
class UserDetailView {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + protected btn_requestViewEmail_Click(sender: object, e: EventArgs): void()
}

UserDetailView --|> System.Web.UI.Page
class ViewProfile {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private SetupPage(): void()
  + private ResetPage(): void()
  + private buildSystemSelectiondata(isExternal: bool): DataTable()
  + private UpdateGVRows(dr: DataRow, isExternal: bool): void()
  + protected btn_externalNext_Click(sender: object, e: EventArgs): void()
  + protected btn_internalNewSave_Click(sender: object, e: EventArgs): void()
}

ViewProfile --|> System.Web.UI.Page
class ViewSignUpStatus {
  + protected Page_Load(sender: object, e: EventArgs): void()
  + private SetupPage(dsUser: DataSet): void()
  + private ResetPage(): void()
  + protected btn_externalBack_Click(sender: object, e: EventArgs): void()
  + protected btn_internalBack_Click(sender: object, e: EventArgs): void()
  + protected btn_resendRegistrationLink_Click(sender: object, e: EventArgs): void()
}

ViewSignUpStatus --|> System.Web.UI.Page
class PageEventHelper {
  + public override OnOpenDocument(writer: PdfWriter, document: iTextSharp.text.Document): void()
  + public override OnEndPage(writer: PdfWriter, document: iTextSharp.text.Document): void()
  + public override OnCloseDocument(writer: PdfWriter, document: iTextSharp.text.Document): void()
}

PageEventHelper --|> PdfPageEventHelper
class ViewSwitcher {
  + protected Page_Load(sender: object, e: EventArgs): void()
}

ViewSwitcher --|> System.Web.UI.UserControl
@enduml
